[tool.poetry]
name = "attachment-service"
version = "0.1.0"
description = ""
authors = ["Your Name <your@email.com>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
asyncpg = "^0.31"
sqlalchemy = "^2.0"
alembic = "^1.14"
pydantic = "^2.10"
pydantic-settings = "^2.7"
aio-pika = "^9.6.2"
aiobotocore = { version = "^2.13", extras = ["boto3"] }
tenacity = "^9.0"
colorama = "^0.4"
opentelemetry-api = "^1.25"
opentelemetry-sdk = "^1.25"
opentelemetry-exporter-otlp-proto-grpc = "^1.25"
opentelemetry-instrumentation-asyncpg = "^0.63b1"

[tool.poetry.group.dev.dependencies]
ruff = "^0.11"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.ruff]
exclude = [
    ".env",
    ".git",
]
line-length = 120
indent-width = 4
target-version = "py312"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false

[tool.ruff.lint]
extend-select = [
    "E",
    "C",
    "F",
    "I",
    "N",
    "UP",
    "TRY",
    "FURB",
    "PLW",
    "C4",
    "B",
    "RSE",
    "SIM",
    "C90",
]
ignore = ["TRY003", "TRY301"]

[tool.ruff.lint.mccabe]
max-complexity = 6
