sonar.organization=krame1s
sonar.projectKey=Krame1S_task-tracker

sonar.sources=gateway,user_service,task_service,category_service,tag_service,comment_service,attachment_service,chat_service,shared
sonar.exclusions=**/migrations/**,**/__pycache__/**,**/.ruff_cache/**,**/tests/**,**/*.lock

sonar.python.version=3.12
