"""fix_tag_unique_per_user

Revision ID: 021124b35311
Revises: 2b6da7bfcd56
Create Date: 2026-04-28 11:44:20.252105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '021124b35311'
down_revision: Union[str, None] = '2b6da7bfcd56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tag_name'), table_name='tag')
    op.create_unique_constraint('uq_tag_name_created_by', 'tag', ['name', 'created_by'])
    op.create_index('ix_task_owner_id', 'task', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_owner_id', table_name='task')
    op.drop_constraint('uq_tag_name_created_by', 'tag', type_='unique')
    op.create_index(op.f('ix_tag_name'), 'tag', ['name'], unique=True)
    # ### end Alembic commands ###
