"""Initial schema: category table

Revision ID: 5dd73b4f84cf
Revises:
Create Date: 2026-05-28 14:48:01.060472

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5dd73b4f84cf"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "category",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_by", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="categories",
    )
    op.create_index(op.f("ix_categories_category_name"), "category", ["name"], unique=True, schema="categories")
    op.create_index("ix_category_created_by", "category", ["created_by"], unique=False, schema="categories")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_category_created_by", table_name="category", schema="categories")
    op.drop_index(op.f("ix_categories_category_name"), table_name="category", schema="categories")
    op.drop_table("category", schema="categories")
    # ### end Alembic commands ###
