"""create_comment_table

Revision ID: 83ccb6a72e13
Revises:
Create Date: 2026-05-29 15:37:24.133453

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "83ccb6a72e13"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "comment",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("task_id", sa.BigInteger(), nullable=False),
        sa.Column("owner_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="comments",
    )
    op.create_index("ix_comment_owner_id", "comment", ["owner_id"], unique=False, schema="comments")
    op.create_index("ix_comment_task_id", "comment", ["task_id"], unique=False, schema="comments")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_comment_task_id", table_name="comment", schema="comments")
    op.drop_index("ix_comment_owner_id", table_name="comment", schema="comments")
    op.drop_table("comment", schema="comments")
    # ### end Alembic commands ###
