"""create_attachment_table

Revision ID: 7aa7926f10de
Revises:
Create Date: 2026-05-29 18:41:18.463048

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7aa7926f10de"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "attachment",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("task_id", sa.BigInteger(), nullable=False),
        sa.Column("owner_id", sa.BigInteger(), nullable=False),
        sa.Column("key", sa.String(length=1024), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=127), nullable=False),
        sa.Column("size", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
        schema="attachments",
    )
    op.create_index("ix_attachment_owner_id", "attachment", ["owner_id"], unique=False, schema="attachments")
    op.create_index("ix_attachment_task_id", "attachment", ["task_id"], unique=False, schema="attachments")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_attachment_task_id", table_name="attachment", schema="attachments")
    op.drop_index("ix_attachment_owner_id", table_name="attachment", schema="attachments")
    op.drop_table("attachment", schema="attachments")
    # ### end Alembic commands ###
